import React, { useState } from 'react';
import { ChevronDown, HelpCircle } from 'lucide-react';

interface FAQItem {
  question: string;
  answer: string;
}

const FAQS: FAQItem[] = [
  {
    question: 'What videos can I download?',
    answer:
      'LoadVideo can process supported YouTube URLs, including public video watch links, YouTube Shorts, and unlisted videos that you own or have explicit permission to download.',
  },
  {
    question: 'Do I need an account to use LoadVideo?',
    answer:
      'No. You do not need to log in, register, or provide any personal information to fetch and download videos on our website.',
  },
  {
    question: 'What video quality options are available?',
    answer:
      'Available qualities depend directly on the source video provided. Typically, formats include 1080p Full HD, 720p HD, 480p, and 360p in MP4 container format.',
  },
  {
    question: 'Can I extract audio only (MP3 or M4A)?',
    answer:
      'Yes. LoadVideo automatically separates video formats from standalone audio formats (MP3 and M4A) so you can easily download audio-only files.',
  },
  {
    question: 'How long does the download link work?',
    answer:
      'Download links generated by the server are temporary and typically valid for approximately 1 hour (3,600 seconds). We recommend completing your download immediately.',
  },
  {
    question: "Why isn't my video fetching?",
    answer:
      'Ensure the video URL is typed correctly and is publicly accessible. Extremely new videos, private videos, age-restricted videos, or URLs from unsupported platforms may fail processing.',
  },
  {
    question: 'Is there a limit on how many videos I can fetch?',
    answer:
      'To prevent spam and ensure fast service for all users, requests are subject to standard rate limits (5 requests/minute per IP). If you receive a rate limit notice, please wait a moment before trying again.',
  },
];

export const FAQ: React.FC = () => {
  const [openIdx, setOpenIdx] = useState<number | null>(0);

  const toggleIdx = (idx: number) => {
    setOpenIdx(openIdx === idx ? null : idx);
  };

  return (
    <section id="faq" className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="text-center space-y-3 mb-10">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-gray-300 font-bold text-xs uppercase tracking-wider">
          <HelpCircle className="w-3.5 h-3.5 text-[#FF5A00]" />
          <span>Frequently Asked Questions</span>
        </div>
        <h2 className="text-2xl sm:text-4xl font-extrabold text-white">Got Questions?</h2>
        <p className="text-gray-400 text-sm sm:text-base">
          Everything you need to know about fetching and downloading videos.
        </p>
      </div>

      <div className="space-y-3">
        {FAQS.map((faq, idx) => {
          const isOpen = openIdx === idx;
          return (
            <div
              key={idx}
              className="bg-[#111111] border border-white/[0.08] hover:border-white/20 rounded-xl overflow-hidden transition-colors"
            >
              <button
                onClick={() => toggleIdx(idx)}
                className="w-full px-6 py-4 text-left flex items-center justify-between gap-4 font-bold text-white text-sm sm:text-base"
              >
                <span>{faq.question}</span>
                <ChevronDown
                  className={`w-5 h-5 text-gray-400 shrink-0 transition-transform duration-200 ${
                    isOpen ? 'rotate-180 text-[#FF5A00]' : ''
                  }`}
                />
              </button>

              {isOpen && (
                <div className="px-6 pb-4 pt-1 text-xs sm:text-sm text-gray-400 leading-relaxed border-t border-white/5 animate-fade-in">
                  {faq.answer}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
};
